language: php

sudo: required
dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

addons:
  apt:
    packages:
      - apache2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - bash travis-scripts/setup-php-fpm.sh
  - bash travis-scripts/setup-apache.sh

script:
  - tests/check_php_parse_errors.sh
  - php install-dev/index_cli.php --language=en --country=us --domain=localhostt --db_name=prestashop.unit.test --db_create=1 --name=prestashop.unit.test --password=123456789
  - cd tests && bash getcomposer.sh && php composer.phar install && php vendor/bin/phpunit -c .
